version: 2

project_name: bridge

builds:
  - id: bridge
    main: ./cmd/bridge/
    binary: bridge
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: bridge
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "bridge_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - profiles/*
      - specializations/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
