name: Bug report
description: Report unexpected behavior or a defect
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: input
    id: version
    attributes:
      label: BRIDGE version
      description: For example, v2.1.0 or main
      placeholder: v2.1.0
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List exact steps so we can reproduce the issue
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, shell, and relevant CLI/tool versions
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant output or attach screenshots
